=== 6chtom/lbr_fri_ros2_stack/third_party/KinematicsLib/dat/Devices/LBR_Med_7_R800_MF_SC_FLR/Config/System/Common/Schemes/NextGenDriveTech.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="Version.xsd"/>
  <xs:element name="CommonConfig">
    <xs:complexType>
      <xs:attribute name="SdoPollIntervall" use="optional" default="2.0">
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:minInclusive value="0.5"/>
            <xs:maxInclusive value="10.0"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Axis">
    <xs:complexType>
      <xs:attribute name="ID" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="255"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="SupplyChannel" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="16"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="ConfigFile" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="tSensor">
    <xs:attribute name="ID" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:int">
          <xs:minInclusive value="1"/>
          <xs:maxInclusive value="255"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="ConfigFile" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:element name="AxisConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Axis" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="tSensorConfig">
      <xs:sequence>
         <xs:element name="Sensor" type="tSensor" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  <xs:element name="DriveTech">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Version"/>
        <xs:element ref="AxisConfig"/>
        <xs:element name="SensorConfig" type="tSensorConfig" minOccurs="0"/>
        <xs:element name="SupplyConfig">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Supply" minOccurs="0" maxOccurs="10">
               <xs:complexType>
                  <xs:simpleContent>
                     <xs:extension base="xs:string">
                        <xs:attribute name="Capacity" type="xs:double"/>
                        <xs:attribute name="ConfigFile" type="xs:string"/>
                     </xs:extension>
                  </xs:simpleContent>
               </xs:complexType>
            </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="FastMeasuring">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Channel" minOccurs="0" maxOccurs="8">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="ID" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="Description" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element ref="CommonConfig" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== 6chtom/lbr_fri_ros2_stack/third_party/KinematicsLib/dat/Devices/LBR_Med_7_R800_MF_SC_FLR/Config/User/Common/Mada/NextGenDriveTech.xml
<?xml version="1.0" encoding="UTF-8"?>
<DriveTech xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/NextGenDriveTech.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Version Label="">
		<Info Version="KUKA V8.3" />
		<Schema Version="3" />
	</Version>
	<AxisConfig>
		<Axis ID="1" SupplyChannel="1" ConfigFile="Mada/NGAxis/A1.xml" />
		<Axis ID="2" SupplyChannel="1" ConfigFile="Mada/NGAxis/A2.xml" />
		<Axis ID="3" SupplyChannel="1" ConfigFile="Mada/NGAxis/E1.xml" />
		<Axis ID="4" SupplyChannel="2" ConfigFile="Mada/NGAxis/A3.xml" />
		<Axis ID="5" SupplyChannel="2" ConfigFile="Mada/NGAxis/A4.xml" />
		<Axis ID="6" SupplyChannel="2" ConfigFile="Mada/NGAxis/A5.xml" /> 
		<Axis ID="7" SupplyChannel="2" ConfigFile="Mada/NGAxis/A6.xml" />
	</AxisConfig>
	<SensorConfig>
    </SensorConfig>
	<SupplyConfig>
		<Supply>Supply/Supply_LBR5_A1_A2_E1.xml</Supply>
		<Supply>Supply/Supply_LBR5_A3_A4_A5_A6.xml</Supply>
	</SupplyConfig>
	<FastMeasuring>
		
	</FastMeasuring>
   <CommonConfig SdoPollIntervall="2.0"/>
</DriveTech>
